services:
    coosos.tag_bundle.tags_type:
        class: Coosos\TagBundle\Form\Type\TagsType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    coosos.tag_bundle.tag_extension:
        class: Coosos\TagBundle\Twig\TagExtension
        tags:
            - { name: twig.extension }
