<?php

namespace Coosos\TagBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * @param null|string $searchTag
     * @param string      $category
     * @param int         $maxResult
     * @return array
     */
    public function getTagList($searchTag = null, $category = null, int $maxResult = null)
    {
        $query = $this->createQueryBuilder("t");

        $query->select("t");

        if ($category) {
            $query
                ->andWhere("t.category = :category")
                ->setParameter("category", $category);
        }

        if ($searchTag) {
            $query
                ->andWhere("t.name LIKE :tag")
                ->setParameter("tag", "%" . $searchTag . "%");
        }

        if ($maxResult) {
            $query
                ->setMaxResults($maxResult);
        }

        return $query->getQuery()->getResult();
    }
}
